[package]
name = "yukino-attribute-reader"
version = "0.1.0"
authors = ["dark-flames <dark_flames@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.syn]
version = "1.0.19"

[dependencies.quote]
version = "1.0.4"

[lib]
proc-macro = true
